### ISSUE TITLE
Upstream time 1.9.1+

### ISSUE THREAD

**Issue by denji** [x-v8/ngx-http-stub-status-rt#1]
http://nginx.org/en/docs/http/ngx_http_upstream_module.html#var_upstream_connect_time

* `$upstream_connect_time` — keeps time spent on establishing a connection with the upstream server (`1.9.1`); the time is kept in seconds with millisecond resolution. In case of SSL, includes time spent on handshake. Times of several connections are separated by commas and colons like addresses in the `$upstream_addr` variable.
* `$upstream_header_time` — keeps time spent on receiving the response header from the upstream server (`1.7.10`); the time is kept in seconds with millisecond resolution. Times of several responses are separated by commas and colons like addresses in the `$upstream_addr` variable.
* `$upstream_response_time` — keeps time spent on receiving the response from the upstream server; the time is kept in seconds with millisecond resolution. Times of several responses are separated by commas and colons like addresses in the `$upstream_addr` variable.

**Comment by detailyang** [comment]
@denji thank you , but our production is using tengine and we have plan to move tengine to nginx. And the key reason for this patch is that we are using [Taobao System Activity Reporter](https://github.com/alibaba/tsar) to monitor every tengine instance. we have to compatible this `tsar --nginx -i 1 -l`

**Comment by detailyang** [comment]
consider closed
